---

# This playbook is used to deploy student-list application based on Docker

# build and push builded images

- name: Log into DockerHub
  docker_login:
    username: "{{ docker_hub_login }}"
    email: "{{ docker_hub_email }}"
    password: "{{ docker_hub_password }}"
  tags:
    - build
- name: create project directory
  file:
    path: "{{ home }}/fake-backend"
    state: directory
  tags:
    - build
    - deploy
- name: copy devops private key file
  copy:
    content: '{{ gitlab_private_key }}'
    dest: "{{ home }}/.ssh/id_rsa"
    owner: centos
  tags:
    - build
    - deploy
- name: retrieve battleboat code source
  git:
    repo: git@github.com:vumay/battleboat-jenkins-CD.git
    dest: "{{ home }}/fake-backend"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ home }}/.ssh/id_rsa"
    version: master
  tags:
    - build
    - deploy

- name: Build api image and push it to Docker Hub
  docker_image:
    path: "{{ home }}/fake-backend"
    name: "{{ docker_hub_login }}/fake-backend"
    push: yes
    tag: jenkinsCD
  tags:
    - build

# docker network

- name: create docker network to interconnect containers
  docker_network:
    name: battleboat_network
  tags:
    - deploy
# deploy api

- name: Deploy mysql db
  docker_container:
    name: db-vumay
    hostname: db-vumay
    image: mysql:5.7
    state: started
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root-vumay"
      MYSQL_DATABASE: "battleboat"
      MYSQL_USER: "battleuser"
      MYSQL_PASSWORD: "battlepass"
    networks:
      - name: battleboat_network
    ports:
      - "3306:3306"
  tags:
    - deploy

# deploy frontend

- name: Deploy frontend
  docker_container:
    name: battleboat
    image: vumay/fake-backend:v1
    state: started
    networks:
      - name: battleboat_network
    volumes:
      - "{{ home }}/battleboat:/etc/backend/static"
    environment:
      DATABASE_HOST: "db-vumay"
      DATABASE_PORT: "3306"
      DATABASE_USER: "battleuser"
      DATABASE_PASSWORD: "battlepass"
      DATABASE_NAME: "battleboat"
    ports:
      - "8181:3000"
  tags:
    - deploy
